services:
  chronosync:
    build:
      context: ../../
      dockerfile: ./packages/reader-main/Dockerfile
    restart: always
    container_name: chronosync
    environment:
      # Mainnet
      # API_URLS: 'https://atomone-rest.publicnode.com'
      #
      # Testnet
      API_URLS: 'https://atomone-testnet-1-api.allinbits.services'

      START_BLOCK: '2605764'
      BATCH_SIZE: 50
      MEMO_PREFIX: dither.
      RECEIVER: atone1uq6zjslvsa29cy6uu75y8txnl52mw06j6fzlep
      AUTH: dev
      COMMUNITY_ACCOUNT_V1: atone1uq6zjslvsa29cy6uu75y8txnl52mw06j6fzlep
      # LOG: process.env.LOG === 'true' ? true : false,
    command: [bun, run, start]
