name: Frontend E2E Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.frontend-main }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect frontend-main changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend-main:
              - 'packages/frontend-main/**'

  e2e-tests:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Store Playwright's Version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npx playwright --version | sed 's/Version //')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "version=${PLAYWRIGHT_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ steps.playwright-version.outputs.version }}-${{ runner.os }}-playwright-browsers

      - name: Cache Playwright user data
        uses: actions/cache@v4
        with:
          path: ./packages/frontend-main/playwright/.user-data
          key: playwright-user-data-${{ hashFiles('packages/frontend-main/e2e/setup/*.ts', 'packages/frontend-main/e2e/config/keplr.ts') }}

      - name: Cache Keplr extension
        uses: actions/cache@v4
        with:
          path: ./packages/frontend-main/playwright/.cache
          key: playwright-cache-${{ hashFiles('packages/frontend-main/e2e/config/keplr.ts') }}

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        working-directory: packages/frontend-main
        run: pnpm test:e2e --headed

      - name: Upload playwright results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-results
          path: |
            packages/frontend-main/test-results/
            packages/frontend-main/playwright-report/
          retention-days: 1
          if-no-files-found: ignore
