name: Frontend Build Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.frontend-main }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect frontend-main changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend-main:
              - 'packages/frontend-main/**'

  frontend-build-check:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm with npm
        run: npm install -g pnpm

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Verify Build
        working-directory: ./packages/frontend-main
        run: pnpm build
