name: '[Mainnet] Frontend'

on:
  push:
    tags:
      - 'frontend/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from tag
        id: git_tag
        run: |
          VERSION="${GITHUB_REF_NAME#frontend/-}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --context production --prod --message ${{ steps.get_tag.outputs.version }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
