name: Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package name to publish
        required: true
        type: choice
        options:
          - lib-api-types
          - lib-event-consumer

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.2

      - name: Set up Node.js for NPM publish
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          scope: '@dither.chat'

      - name: Install dependencies
        run: |
          cd ./packages/${{ github.event.inputs.package }}
          bun install

      - name: Build package
        run: |
          cd ./packages/${{ github.event.inputs.package }}
          bun run build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./packages/${{ github.event.inputs.package }}
          bun publish --access public --no-git-checks
